version: 2
volumes:
  home-dir: {}
  host-keys: {}
services:
  dev:
    # image: quay.io/goodguide/dev
    build: .

    privileged: true # not at all necessary, just might be helpful

    ports:
      - '22' # sshd
      - '60001/udp' # mosh server

    restart: always

    pid: host

    volumes:
      # mount docker socket into container so you can do things like run
      # docker-compose from projects you're working on
      - '/var/run/docker.sock:/var/run/docker.sock'

      # workspace directory (if ever using docker within this container, makes
      # it easier if the path inside the container matches the path on the
      # host)
      - '/code:/code'

      # consistent home and host-keys directories
      - 'home-dir:/root'
      - 'host-keys:/etc/ssh/ssh_host_keys'

    hostname: 'dev-${USER}'
